spring.application.name=madaporc
server.port=8082
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://localhost:5432/madaporc
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true