spring.application.name=madaporc
server.port=8082

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/madaporc
spring.datasource.username=noah
spring.datasource.password=noah
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=optional:classpath:schema.sql
spring.sql.init.data-locations=optional:classpath:data.sql
spring.sql.init.continue-on-error=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.expediteur=noahtown011@gmail.com
app.mail.mot-de-passe=znbt mfaw yhwi tgtm
app.mail.destinataire=mickaellaandriamarondraibe@gmail.com